permissions:
  id-token: write
  contents: read 
name: Terraform Destroy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy (e.g., prod)'
        required: true
        default: 'prod'
      service:
        description: 'Service to destroy (e.g., webserver-cluster)'
        required: true
        default: 'webserver-cluster'
      confirm_destroy:
        description: 'Type "destroy" to confirm'
        required: true

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_destroy == 'destroy'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to AWS using OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # specify the IAM role to assume here
          role-to-assume: "arn:aws:iam::418272752575:role/github-actions-oidc-example20250511055154010500000001"
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0  
          terraform_wrapper: false

      - name: Terraform Destroy with Dependencies
        working-directory: ./prod/services/webserver-cluster
        run: |
          terraform init
          # First destroy resources that depend on security groups
          terraform destroy -target=module.webserver_cluster.aws_autoscaling_group.example -auto-approve
          terraform destroy -target=module.webserver_cluster.aws_lb.example -auto-approve
          # Then destroy security groups
          terraform destroy -target=module.webserver_cluster.aws_security_group.instance -auto-approve
          terraform destroy -target=module.webserver_cluster.aws_security_group.alb -auto-approve
          # Finally destroy everything else
          terraform destroy -auto-approve