permissions:
  id-token: write
  contents: read 
name: Terraform Apply
on:
  push:
    branches:
      - main

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to AWS using OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # specify the IAM role to assume here
          role-to-assume: "arn:aws:iam::418272752575:role/github-actions-oidc-example20250511055154010500000001"
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0  
          terraform_wrapper: false

      # - name: Check and Force Unlock MySQL State (if needed)
      #   working-directory: ./prod/data-stores/mysql
      #   run: |
      #     terraform init
      #     # Try to apply with a timeout
      #     timeout 30s terraform apply -auto-approve || \
      #     # If it times out or fails, try to identify if it's a lock issue
      #     if terraform state list 2>&1 | grep -q "Error acquiring the state lock"; then
      #       # Extract lock ID and force unlock
      #       LOCK_ID=$(terraform state pull 2>&1 | grep -o "ID:[[:space:]]*[a-z0-9-]*" | cut -d' ' -f2)
      #       if [ ! -z "$LOCK_ID" ]; then
      #         echo "Force unlocking state with ID: $LOCK_ID"
      #         terraform force-unlock -force $LOCK_ID
      #         # Try apply again after unlocking
      #         terraform apply -auto-approve
      #       fi
      #     fi

      # - name: Check and Force Unlock Webserver Cluster State (if needed)
      #   working-directory: ./prod/services/webserver-cluster
      #   run: |
      #     terraform init
      #     # Try to apply with a timeout
      #     timeout 30s terraform apply -auto-approve || \
      #     # If it times out or fails, try to identify if it's a lock issue
      #     if terraform state list 2>&1 | grep -q "Error acquiring the state lock"; then
      #       # Extract lock ID and force unlock
      #       LOCK_ID=$(terraform state pull 2>&1 | grep -o "ID:[[:space:]]*[a-z0-9-]*" | cut -d' ' -f2)
      #       if [ ! -z "$LOCK_ID" ]; then
      #         echo "Force unlocking state with ID: $LOCK_ID"
      #         terraform force-unlock -force $LOCK_ID
      #         # Try apply again after unlocking
      #         terraform apply -auto-approve
      #       fi
      #     fi

      - name: Terraform init and apply MySQL
        id: mysql
        working-directory: ./prod/data-stores/mysql
        run: |
          terraform init
          terraform apply -auto-approve
        # This ensures the step is marked as failed if any command fails
        shell: bash {0}

      # This step will only run if the MySQL step succeeds
      - name: Terraform init and apply Webserver Cluster
        if: success() && steps.mysql.outcome == 'success'
        working-directory: ./prod/services/webserver-cluster
        run: |
          terraform init
          terraform apply -auto-approve
        shell: bash {0}