permissions:
  id-token: write
  contents: read 
name: Terraform Apply
on:
  push:
    branches:
      - main

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to AWS using OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # specify the IAM role to assume here
          role-to-assume: "arn:aws:iam::418272752575:role/github-actions-oidc-example20250511055154010500000001"
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0  
          terraform_wrapper: false

      - name: Terraform Init and Apply
        working-directory: ./prod/services/webserver-cluster
        run: terraform destroy -auto-approve
        # run: |
        #   terraform init
        #   terraform apply -auto-approve
